### ISSUE TITLE
KeyError: 2 when converting

### ISSUE THREAD

**Issue by LotfiKobrosly** [paulmelis/nano-tools#1]
Hi! I am using the nano-tools in this repository on the test network I created on my computer using docker-compose, and I have two errors (which I cannot understand):
1. Creating the dump for the database:
When I run `python3 dump_wallet_db.py` , it tries to accede to the dump but it stops after a second with this response:
```
Traceback (most recent call last):
  File "dump_wallet_db.py", line 225, in <module>
    subdb = env.open_db(subdbname.encode())
lmdb.ReadonlyError: mdb_dbi_open: Permission denied
```

2. When running `./conv2sqlite.py convert` after exporting LC_ALL=C.UTF-8 and LANG=C.UTF-8 I get:
```
Reading the Nano database at /root/RaiBlocksTest/data.ldb
Processing "change" blocks ... 0 (0.000s)
Processing "open" blocks ... 1 (0.004s)
Processing "receive" blocks ... 0 (0.000s)
Processing "send" blocks ... 0 (0.000s)
Storing account info ... 2 (0.004s)
Deriving per-block info
Reconstructing account chains ... 1 (0.000s)
Traceback (most recent call last):
  File "./conv2sqlite.py", line 858, in <module>
    cli()
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 722, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 697, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 895, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "./conv2sqlite.py", line 843, in convert
    ctx.forward(derive_block_info)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 553, in forward
    return self.invoke(cmd, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 535, in invoke
    return callback(*args, **kwargs)
  File "./conv2sqlite.py", line 789, in derive_block_info
    block_to_balance, block_to_amount)
  File "./conv2sqlite.py", line 613, in compute_block_balances_and_amounts
    assert block_to_type[send_block] == 'send'
KeyError: 2
``` 

Can anyone help me understand and fix this please? Thank's a lot!

**Comment by paulmelis** [comment]
For the second issue I suspect that the new universal blocks are somehow to blame, as I haven't added support for them.

For the first issue I can't directly see what is happening. What is the size of the RaiBlocks folder you're working with?
